apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::026152624358:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::026152624358:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-AD47VM8DVM2O
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-02T12:11:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1404"
  uid: d07d275f-1624-494d-bd28-47195ae6617b
